// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseEditor: typeof import('./src/components/BaseEditor.vue')['default']
    Card: typeof import('./src/components/Card.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HeaderContent: typeof import('./src/components/Write/HeaderContent.vue')['default']
    HeaderTool: typeof import('./src/components/Write/HeaderTool.vue')['default']
    ImageSelects: typeof import('./src/components/Write/ImageSelects.vue')['default']
    Main: typeof import('./src/components/message/main.vue')['default']
    Modal: typeof import('./src/components/Modal.vue')['default']
    Pager: typeof import('./src/components/Pager.vue')['default']
    Popover: typeof import('./src/components/Popover.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TagSelects: typeof import('./src/components/Write/TagSelects.vue')['default']
  }
}

export {}
